# test logistic regression model
_test: true
model_name: LogisticRegression
random_state: 42
yaml_file: examples/config/modelconfig/logisticregression.yaml

configurations:
  train:
    train_test_split:
      test_size: 0.2

    model_params:
      n_jobs: -1

    cross_validation_params:
      cv: 5
      scoring: accuracy
      refit: true

  search:
    model_selection:
      method: GridSearchCV

      GridSearchCV:
        cv: 5
        scoring: accuracy
        refit: true
        param_grid:
          C: [1.0, 0.5, 0.25, 0.125]
          penalty: ["l1", "l2"]

      RandomizedSearchCV:
        param_distributions:
          C: [1.0, 0.5, 0.25, 0.125]
          penalty: ["l1", "l2"]
        n_iter: 10
        random_state: 42
